### ISSUE TITLE
No data posted when type is 'json'

### ISSUE THREAD

**Issue by Drumkruk** [pebble/pebblejs#10]
When posting data through ajax with the following setup:

    ajax(
    {
      url: URL,
      method: 'post',
      type: 'json',
      data: {
        auth : 'test'
      }
    },
    function(data) {
      // Success!
      console.log(JSON.stringify(data));
    },
    function(error) {
      // Failure!
      console.log('no response');
    }
    );

Php is not receiving any post data. Shouldn't the Content-Type header be application/x-www-form-urlencoded as it is sending data? Now it is specifically set to 'application/json' in the code, which doesn't post the data? 

The post data is send when the type is 'html'. 

Please help me out, because I really dig Pebble.js

**Comment by Meiguro** [comment]
Thanks, the documentation has been updated! It sort of shoves a lot of into into that little box -- I should structure it better in the future.
