### ISSUE TITLE
Question: compatible with pebble round?

### ISSUE THREAD

**Issue by kadamwhite** [pebble/pebblejs#116]
I cannot find any indication in the documentation whether an app made with this library can be compatible with the new pebble round. Any clarification would be appreciated, thanks!

**Comment by Meiguro** [comment]
Sorry about that, I have my hands quite full, but it is planned that Pebble.js will support Chalk. At the moment, it is currently just compile support. There is a WIP to bring the Card, status bar, and action bar to Basalt and Chalk standards, and Menu being hopefully the last.

This is being tracked by #96 which was amusingly made seconds after the PTR announcement. I may post my progress there when I feel I have a good estimate.

**Comment by maxogden** [comment]
Found this thread after trying to build for PTR on CloudPebble and finding out the app shows up as 'Unsupported apps'. +1 to Pebble Time Round support, especially with CloudPebble!

**Comment by ToemD** [comment]
+1, especially with CloudPebble!

**Comment by alexmihai** [comment]
+1

Thanks for this wonderful library!

**Comment by Meiguro** [comment]
Thanks for the support everyone, I've finally managed to improve Pebble.js and had Katharine use this updated version in CloudPebble, so it's now compatible! Open new tickets for any particular issues that you find.
