### ISSUE TITLE
Microphone supported platform reports "noMicrophone"

### ISSUE THREAD

**Issue by Meiguro** [pebble/pebblejs#117]
*This issue is occurring for one developer.*

Please try this snippet in a new CloudPebble Pebble.js project and post back if the issue occurs in the new project on your Pebble Time flavored watch.

```
var UI = require('ui');
var Voice = require('ui/voice');

var main = new UI.Card({
  fullscreen: true,
  title: 'Voice!',
  body: 'Press select.',
});

main.show();

main.on('click', 'select', function(e) {
  Voice.dictate('start', function(e) {
    console.log(e.err || e.transcription);
    var result = new UI.Card({
      title: 'Transcription',
      body: e.err || e.transcription,
    });
    result.show();
  });
});
```

**Comment by TheNetStriker** [comment]
This sample works for me, but in my existing project I still got the error. (It's basically the OpenHAB Pebble application I try to modify) I've uploaded my code changes here: https://github.com/TheNetStriker/openhab.pebble/commit/0b021c986ba4cd2379538d9928526361ac2dc8e2

What could cause this problem?

**Comment by Meiguro** [comment]
It's possible your project is in a weird state, such as only compiling the Aplite build and not the Basalt build. The sample was made to narrow the issue down, it probably isn't something caused by OpenHAB.

I would check your Compilation > Emulator tab. When you compile, it should light up Aplite and Basalt. If only Aplite is lit up, your project hasn't gracefully upgraded for some reason, and you should contact devsupport `at` pebble.com about this. If Basalt does light up, when running in the emulator, do you see the microphone animation? Let me know what you find out.

If Aplite is not lit up, a work around is to start a new project importing your repository, but you should still contact devsupport with your issue so that others with the same problem can be addressed.

You can also download the latest pbz as a compiler artifact and unzip the pbz (it is a zip file). See if it has a basalt directory. If it doesn't, that would confirm that it isn't making basalt builds for some reason.

**Comment by TheNetStriker** [comment]
Thanks for the hint, I've created a new project and imported the (already to sdk 3 updated) sources from GitHub and then the Basalt build appeared in the emulator tab. Now the voice api is working!

I only have one last question. On the lines with a "for (var xxx in yyy)" I get the following warning:
'for of' is available in ES6 (use 'esversion:6') or Mozilla JS extensions (use moz).

I am using Google Chrome. How can I get rid of this warning?

**Comment by Meiguro** [comment]
Add `/* jshint esversion: 6 */` to the top of every .js file and jshint will understand you want to use ES6 syntax.

If you look closely, you'll see that it is `for (var ... of ...)`, unless that's what you meant to point out
https://github.com/TheNetStriker/openhab.pebble/blob/0b021c986ba4cd2379538d9928526361ac2dc8e2/src/page.js#L122
> `for (var widget of widgets) {`

Notice the "of" instead of "in". The repo you forked has been using the "of" syntax.

This is a jshint warning that is attempting to tell you that "for of" is an ES6 only feature, and thus CloudPebble does not guarantee that your script will run in an ES6 compatible runtime.

You have two options, changing all "of" to "in" for maximum mobile phone compatibility, or you silence the warning, possibly having issues on certain mobile phones. I imagine though that this is a private project meant to only work on your phones, so you probably just want to silence the warning as directed at the top.

**Comment by TheNetStriker** [comment]
Thanks for the help. I've added /* jshint esversion: 6 */ to the files and now the warning is gone.

**Comment by TheNetStriker** [comment]
I've noticed one small issue regarding the UI. After returning from the dictation window to the app window the app window is displayed in fullscreen mode and I found no way to disable fullscreen mode. How can I disable the fullscreen mode after returning from the dictation window?

**Comment by Meiguro** [comment]
Yes, I noticed that too. Unfortunately for now the solution is to keep using fullscreen mode. You can try setting the status bar again as a work around with `wind.fullscreen(false)`, but I'm not sure that will work.

I have a PR that changes the way the status bar and action bar works which may fix the problem, after enough testing there may be another Pebble.js update to fix these issues.

**Comment by TheNetStriker** [comment]
I've tried setting the fullscreen attribute after the menu is created, but that doesn't seam to work. I will wait for this to be fixed in Pebblejs.
