### ISSUE TITLE
ajax() calling the success handler twice when sync: false

### ISSUE THREAD

**Issue by tbuehlmann** [pebble/pebblejs#131]
So I stumbled over this while hacking my first Pebble.js project. When using the ajax library and the `async: false` option, the success handler is called twice.

Running the following through the CloudPebble Basalt Emulator:

```javascript
// app.js

var ajax = require('ajax');

ajax({url: 'https://www.google.com/', async: false}, function() {
  console.log("foo");
});
```

outputs the following:

```
[PHONE] pebble-app.js:?: foo
[PHONE] pebble-app.js:?: foo
```

**Comment by Meiguro** [comment]
Wow, thanks for catching that! I've just put up a fix on master. It'll be on CloudPebble as soon as I have completed writing documentation for all the new features that will be introduced. You can test the fix with the local SDK (or someone else can chime in and verify the fix).

**Comment by tbuehlmann** [comment]
Great, I'll wait for it to be on CloudPebble. Thank you!

**Comment by Meiguro** [comment]
The fix is now on CloudPebble! Sorry for the long wait. Re-open if you have any issues.
