### ISSUE TITLE
Blank space at the bottom of a menu (Basalt & Aplite)

### ISSUE THREAD

**Issue by fletchto99** [pebble/pebblejs#139]
After commit 38a07351188195e08cf8e721c508dfc5b67ed18a there appears to be some random blank space at the bottom of the menu.

![pebble_screenshot_2016-02-14_00-49-17](https://cloud.githubusercontent.com/assets/718681/13032144/bda6a496-d2b5-11e5-8005-9f9cffc991a6.png) ![pebble_screenshot_2016-02-14_00-49-42](https://cloud.githubusercontent.com/assets/718681/13032145/bee11332-d2b5-11e5-9566-7cce2708b267.png)

It appears to be the space of about the status bar. Please advise if any code examples are required.

**Comment by fletchto99** [comment]
Hmm it's hard to see on those images. I have added an outline to the image to demonstrate the issue.
![pebble_screenshot_2016-02-14_00-49-17](https://cloud.githubusercontent.com/assets/718681/13032154/2b2ccdce-d2b6-11e5-8991-9fd789f07be2.png) ![pebble_screenshot_2016-02-14_00-49-42](https://cloud.githubusercontent.com/assets/718681/13032155/3a6e3a16-d2b6-11e5-9629-aa847dc8c58d.png)

**Comment by Meiguro** [comment]
Whoops! I've updated the demo app to make that issue more obvious in the future, although eventually I need to add tests.

**Comment by fletchto99** [comment]
Appears to have fixed the issue, thanks @Meiguro!
