### ISSUE TITLE
Menu section titles not centred [chalk]

### ISSUE THREAD

**Issue by fletchto99** [pebble/pebblejs#140]
As of commit 38a07351188195e08cf8e721c508dfc5b67ed18a (the chalk update) menu section headers are not centred. 

![pebble_screenshot_2016-02-14_00-50-13](https://cloud.githubusercontent.com/assets/718681/13032161/7b21c8b6-d2b6-11e5-89fc-65686c29c82a.png)

**Comment by Meiguro** [comment]
Ah, I missed this. On another note, I don't particularly recommend using section titles. They're useful for complex lists, but if you noticed, the Pebble firmware doesn't use them anywhere in 3.0, so it's very likely there are many other edge cases dealing with using section titles. Firmware 3.0 avoids section titles by increasing fan out to more windows, or reducing overall complexity of an app.

**Comment by fletchto99** [comment]
Thanks for the fix! I'll look into updating my apps to conform more to the 3.X standards
