### ISSUE TITLE
Card text is cut off [Chalk]

### ISSUE THREAD

**Issue by fletchto99** [pebble/pebblejs#141]
Sometimes the text for a card is slightly too wide and gets cut off by the edges. Perhaps increasing the insets will help?

![pebble_screenshot_2016-02-14_00-50-31](https://cloud.githubusercontent.com/assets/718681/13032170/ad19885e-d2b6-11e5-920a-a0deaa031649.png) ![pebble_screenshot_2016-02-14_00-50-55](https://cloud.githubusercontent.com/assets/718681/13032171/ae7d6a76-d2b6-11e5-9028-128edb068f37.png)

**Comment by Meiguro** [comment]
Ah, this was caused by offsetting the window's inner layer by the status bar layer. Master is updated to use the layer convert to screen functions.

**Comment by fletchto99** [comment]
Thanks for the fix, appears to be working now!
