### ISSUE TITLE
Card text is truncated [Chalk]

### ISSUE THREAD

**Issue by fletchto99** [pebble/pebblejs#142]
Sometime the text on a card is truncated and just has ellipses at the end.

Chalk results: 
![pebble_screenshot_2016-02-14_00-52-29](https://cloud.githubusercontent.com/assets/718681/13032181/f850db38-d2b6-11e5-892d-8e2667cfa0fc.png)

Expected (basalt) results:

![pebble_screenshot_2016-02-14_00-52-35](https://cloud.githubusercontent.com/assets/718681/13032182/0233606c-d2b7-11e5-9b29-cd0f0a2b657b.png)

**Comment by Meiguro** [comment]
Hmm, do you have a minimal example? Or does it still happen with the recent changes? Is scrollable set to true?

**Comment by fletchto99** [comment]
I am unable to page down any further. The latest version of master also broke Basalt & Aplite, the text is cut off by about the height of a status bar. Both of these images are scrolled down all the way.

Basalt: Missing the word meetup (notice it's cut off, I'm assuming this is related to #139)
![pebble_screenshot_2016-02-14_12-06-37](https://cloud.githubusercontent.com/assets/718681/13035038/a7658aea-d313-11e5-848e-b4fc93b8405f.png)

Chalk: Cut off while scrolling, cannot scroll any further.
![pebble_screenshot_2016-02-14_12-06-50](https://cloud.githubusercontent.com/assets/718681/13035039/adfb5e5c-d313-11e5-8a19-7fb36494e0e0.png)


Minimal example code:

````js
var UI = require('ui');

var main = new UI.Card({
  title: 'Pebble From A to Z series: Pebble App Development with Pebble.js and CloudPebble',
  body: 'Date: 27-02-2016 1:00pm\n'+
        'Location: Grovo\n'+
        'Distance: 334.1mi\n' +
        'Address: 3 Park Avenue, 30th Floor\n' +
        'New York, NY, us\n' +
        'Attending: 5 Pebblers\n' +
        'Host Group: Pebble\'s NYC Meetup',
  scrollable: true
});

main.show();
````

**Comment by Meiguro** [comment]
Tanks for the minimal example! This was a tricky one, turns out I was accidentally also using the content width for rendering. See if this fixes the issue.

**Comment by fletchto99** [comment]
This fixes the original text being truncated issue on chalk however the cut off text still occurs on basalt. I will open a new ticket to address this issue since the original issue here is fixed. Thanks again @Meiguro!
