### ISSUE TITLE
Scrollable cards cut off [Aplite & Basalt]

### ISSUE THREAD

**Issue by fletchto99** [pebble/pebblejs#143]
Card with the scrollable property are cut short in the Aplite and Basalt platforms. Notice how the word Meetup is cut off at the bottom, even though the card is scrolled all the way to the bottom.

![a7658aea-d313-11e5-848e-b4fc93b8405f](https://cloud.githubusercontent.com/assets/718681/13037809/db479054-d356-11e5-8e30-53fc965dac7c.png)

Minimal example code:

````js
var UI = require('ui');

var main = new UI.Card({
  title: 'Pebble From A to Z series: Pebble App Development with Pebble.js and CloudPebble',
  body: 'Date: 27-02-2016 1:00pm\n'+
        'Location: Grovo\n'+
        'Distance: 334.1mi\n' +
        'Address: 3 Park Avenue, 30th Floor\n' +
        'New York, NY, us\n' +
        'Attending: 5 Pebblers\n' +
        'Host Group: Pebble\'s NYC Meetup',
  scrollable: true
});

main.show();
````

**Comment by Meiguro** [comment]
I had disabled a little too much layer adjustment in fixing the menu issue, the commit attempts for fix it for round and rect. An extra commit adds more margin for the last line of text.

**Comment by fletchto99** [comment]
Works like a charm! Thanks @Meiguro
