### ISSUE TITLE
menu.selection(function(e){...}) Can't find variable: callback

### ISSUE THREAD

**Issue by ToemD** [pebble/pebblejs#149]
I'm new here, so I don't want to check in my changes before I have used github for a while, so I will report the issue here:
`menu.selection(function(e){...});`

throws the following error:
> JavaScript Error:
> ReferenceError: Can't find variable: callback
>     at selection (ui/menu.js:311:35)

I think the issue is in ui/menu.js row 315:
`this._selections.push(callback);`
has to be changed to
`this._selections.push(callback_or_sectionIndex);`

**Comment by Meiguro** [comment]
I've just merged #133 which fixes this issue. Let me know if it works for you now!

**Comment by Meiguro** [comment]
The fix is now on CloudPebble as well. Re-open if you still have issues.
