### ISSUE TITLE
A way to know whether it's Pebble Round or not in javascript?

### ISSUE THREAD

**Issue by sunshineyyy** [pebble/pebblejs#151]
Is there a way to know whether it's a round or rectangular in javascript? I know in C it has something like defined(PBL_RECT) or PBL_IF_RECT_ELSE("rectangular", "round"). Can we have sort of similar interface in javascript to know whether we are dealing with Pebble Round or not? I knew the recent updates made Menu, Card stuff round compatible and it looks really great. I am building some customized window so I need a way to know whether it's round or rectangular. Thanks a lot!

**Comment by fletchto99** [comment]
`Pebble.getActiveWatchInfo()` will give all of the information required.

Alternatively you can use the platform module built into PebbleJS.

````js
var platform = require('platform');
platform.version(); //Will be one of ['aplite', 'basalt', 'chalk']
````

**Comment by sunshineyyy** [comment]
I forgot to say but this totally works! Thanks @fletchto99!

**Comment by Meiguro** [comment]
I also just added a new Feature module that handles this use case better

```js
var Feature = require('platform/feature');
var x = Feature.rectangle(40, 50);
var y = Feature.round(20, 30);
var color = Feature.color('red', 'white');
```

This is only in master right now, but will be the way to do feature detection in the future. As you can see it lives in platform, so platform isn't going away. You would still use platform for differentiating features that Feature doesn't handle yet.
