### ISSUE TITLE
[Bug] Run time error when show UI.card()

### ISSUE THREAD

**Issue by yaoyuyang** [pebble/pebblejs#152]
Not sure if this a problem particular to me or other people have had this problem. Using the current version of pebblejs, I have the following error when install the app on Pebble if I define a new UI.card() and try to show it.
The example code in pebblejs:

```
var main = new UI.Card({
  title: 'Pebble.js',
  icon: 'images/menu_icon.png',
  subtitle: 'Hello World!',
  body: 'Press any button.',
  subtitleColor: 'indigo', // Named colors
  bodyColor: '#9a0036' // Hex colors
});
main.show();
```

when install on Pebble will give:

```
ault_handling.c:74> App fault! {133215f0-cf20-4c05-997b-3c9be5a64e5b} PC: 0x80000e2 LR: 0x2fc3
Program Counter (PC)    : 0x80000e2  ???
Link Register (LR)      : 0x2fc3     /Users/yaoyu/pebble-dev/pebblejs/src/util/string.h:32
```

This happens both for my [app](https://github.com/sunshineyyy/CatchOneBus) and also the unmodified pebblejs. The error does not happen in simulator. I think this is very similar to what mentioned in [common runtime problem](https://developer.pebble.com/guides/pebble-apps/debugging/runtime-problems). I tried to look at the C code related to this but don't know where exactly is causing the problem.

The Pebble I use is a Pebble Steel with firmware v3.9.2, developer tool I use is Pebble Tool v4.1.1 (active SDK: v3.9.2).

Thanks!

**Comment by Meiguro** [comment]
Thanks for reporting this issue! This was a bit tricky, and also embarrassing. Check out the latest master.

**Comment by fridgecow** [comment]
Is this fixed in cloudpebble? I'm still having this issue.

**Comment by Meiguro** [comment]
This was a master only issue. The example in this ticket was the demo app, which I believe works in CloudPebble currently. If you have a minimal example of your issue on CloudPebble, I can take a look. If you can't create a minimal example, you can export your project for me to look at, but it would take longer to figure out the issue.

**Comment by fridgecow** [comment]
I significantly downsized my app and the problem went away. I do not have git integration enabled, so can't show you the older version where this occurs. It happened when I switched from one UI.Card to another, both of which were quite resource heavy (icon and 3 actionbar images). If the problem returns I will try and create a minimal example.
