### ISSUE TITLE
need a cloudpebble update

### ISSUE THREAD

**Issue by llamahunter** [pebble/pebblejs#156]
Have recent changes been pushed to cloudpebble?  It's unclear.  Documentation on getpebble.com does not show new apis.

**Comment by Meiguro** [comment]
No, not yet. I intend to update the version on CloudPebble once the following are documented:

- [ ] New Card styles
- [ ] Card colors
- [ ] Menu colors
- [ ] Element colors
- [ ] Element borderWidth
- [ ] Line element
- [ ] Radial element
- [ ] Platform module
- [ ] Features module
- [ ] WindowStack module (maybe)
- [ ] Guide on using colors
- [ ] Guide on feature detection
- [ ] Window status nested accessor
- [ ] Window size method
- [ ] Settings config hash option

The following additional features need to be implemented for the documentation:

- [ ] Support clay-style colors 0xRRGGBB
- [ ] Support resource-style formatting for named colors, e.g. `'sunrise-orange'` and `'SUNRISE_ORANGE'`

And perhaps anything else I've missed. I'll update this checklist as I go, I'm likely to begin with supporting the additional ways to specify color.

**Comment by Meiguro** [comment]
Finally merged on CloudPebble! Sorry for the long wait.

**Comment by llamahunter** [comment]
w00t! Thx!
