### ISSUE TITLE
Number conversion to string - Menus

### ISSUE THREAD

**Issue by fletchto99** [pebble/pebblejs#159]
Hey,

The other week I was hosting hackathon and some users were trying to send numbers as the title of the menu. When they did this the sub-title no longer rendered. I've put together a minimal example to replicate this issue:

````js
var UI = require('ui');

new UI.Menu({
    sections: [{
        items: [{
            title: 89,
            subtitle: 'hello world'
        }, {
            title: 92,
            subtitle: 'hellow world'
        }]
    }]
}).show();
````
<img width="155" alt="screen shot 2016-04-14 at 6 55 56 pm" src="https://cloud.githubusercontent.com/assets/718681/14546285/8d92d9c2-0272-11e6-8901-7f9ddc1a9b88.png">

As you can see the title renders fine but the subtitle is not there as expected. The expected output would be: 

<img width="152" alt="screen shot 2016-04-14 at 6 57 27 pm" src="https://cloud.githubusercontent.com/assets/718681/14546333/c4a7e056-0272-11e6-8857-af646f985bd3.png">

**Comment by Meiguro** [comment]
Thanks for catching this one! Let me know if the fix works for you.

**Comment by fletchto99** [comment]
Looks good thanks @Meiguro
