### ISSUE TITLE
[Bug] Menu Screen Dotted Line

### ISSUE THREAD

**Issue by calexander3** [pebble/pebblejs#162]
On the menu screen there is a dotted line that appears below the time and above the menu options.
![b](https://cloud.githubusercontent.com/assets/1903766/15266023/252a2c00-1965-11e6-89fc-547bc759f607.png)

**Comment by Rogoon** [comment]
I think that is by design. 
You should be able to turn it off with something like this: 

'''
var card = new UI.Card({
  status: {
    backgroundColor: backgroundColor,
    separator: 'none'
...
'''

Separator defaults to 'dotted', but can be turned off with 'none'

**Comment by Meiguro** [comment]
Thanks @Rogoon, that's correct!

At first, I tried changing the status bar color to match the background color automatically, but it resulted in some undesired side affects. In either case, you can change the `color`, `backgroundColor`, and `separator`.

```js
var menu = new UI.Menu({
  status: {
    color: 'white'.
    backgroundColor: 'black',
    separator: 'none',
  },
  ...
});
```
at initialization or
```js
menu.status({
  color: 'white'.
  backgroundColor: 'black',
  separator: 'none',
});
```
after the fact, preferably before calling `.show()`.

**Comment by calexander3** [comment]
Totally works. Thanks all I had no idea about the status object.
