### ISSUE TITLE
[Bug] Scrolling issue on Aplite

### ISSUE THREAD

**Issue by bellangerq** [pebble/pebblejs#163]
After updating Pebble.js to the [lastest version](https://developer.pebble.com/blog/2016/05/16/Pebble-JS-Round/), there is a scrolling bug on Aplite on the local SDK (*Basalt and Chalk are working well*) as you can see on this GIF: [http://g.recordit.co/emhdaYO5Rn.gif](http://g.recordit.co/emhdaYO5Rn.gif).

![](http://g.recordit.co/emhdaYO5Rn.gif)

Here is the link to my project: [https://github.com/bellangerq/quebble/tree/scroll](https://github.com/bellangerq/quebble/tree/scroll).

Thanks for helping :)

**Comment by cat-haines** [comment]
@bellangerq thank you for submitting this issue :) We may ask for more information as we try to reproduce..

@Meiguro This might be related to #161? Have we had any other reports of scrolling being jittery on Aplite?

**Comment by Meiguro** [comment]
Ah, I forgot to apply the fix to dynamic windows as well.

**Comment by Meiguro** [comment]
Thanks @cat-haines, that was helpful. This should be the last occurrence, seeing as there are only three types of windows, two of which are scrollable by semi-non-system means.

@bellangerq Nice use of dynamic windows! The fix is on master, I'll request a CloudPebble update.

**Comment by cat-haines** [comment]
@bellangerq - Just tested with your project, and this resolves the issue. 

Please merge master into your project again, and post a comment here saying whether it fixed it for you (once you've got it working we'll close this issue).

**Comment by bellangerq** [comment]
Hey, it's working! The scroll is way better on aplite:)

Thank you so much @cat-haines @Meiguro for your help and the quick answers. Have a nice day!

**Comment by andrei-markeev** [comment]
Still have this bug using CloudPebble... Any plans updating CloudPebble version of Pebble.js with the fix?
