### ISSUE TITLE
Circle seems to be broken

### ISSUE THREAD

**Issue by DavidJFelix** [pebble/pebblejs#32]
Circle only draws a single pixel at the top left corner, regardless of backgroundColor and borderColor:

Reproduce by taking a working square rect and making it a circle:

```
new UI.Circle({
    position: new Vector2(10, 40),
    size: new Vector2(20, 20),
    backgroundColor: 'white',
    borderColor: 'white'
  });
```

**Comment by Meiguro** [comment]
Ah, this somehow slipped me! Circle uses `radius` instead, and I have just corrected the docs. So you would specify `radius: 20,` instead of using `size`.

**Comment by DavidJFelix** [comment]
Nice. this explains my frustration. I just figured it was actually an Oval and Vector2 was valid
