### ISSUE TITLE
console.log not working (SDK 3.0-dp4)

### ISSUE THREAD

**Issue by srabenhorst** [pebble/pebblejs#39]
There is no output for a console.log when I use the emulator (SDK 3.0-dp4) on my mac. On cloudpebble it's working without problems. Is this a known problem? Is there a workaround?

**Comment by Meiguro** [comment]
I use `pebble install --phone=X.X.X.X --logs` with the `--logs` flag when developing locally. Have you tried something similar? There is also a `pebble logs` command for streaming logs after installing.

**Comment by srabenhorst** [comment]
The `--logs` flag did and I was using `--debug`. Thank you very much for the faste answer!
