### ISSUE TITLE
Color on Menu

### ISSUE THREAD

**Issue by ishepard** [pebble/pebblejs#42]
Is there a possibility to add the support for colors on the menu? I wrote a watchapp using pebblejs, but if I add a colored icon on the menu, the result is: 
![pebble-screenshot_2015-03-31_13-19-01](https://cloud.githubusercontent.com/assets/9136821/6917823/8c605836-d7a8-11e4-86de-3a59c848dc96.png)
As you can see, when the item is selected, the icon disappears.

**Comment by sarfata** [comment]
Yes it will be possible. The new menu seen in the kickstarter video is just not yet part of the Pebble SDK. Once it is available in the pebble sdk, we can add it in pebble.js.

Stay tuned!

**Comment by ishepard** [comment]
Hi,
there is still a problem with the image icon of the menu...if set to white the background of the image, I see it correctly, but when I select the item I see it wrong..look at the first item, the not selected one:
![screen shot 2015-04-23 at 11 13 39](https://cloud.githubusercontent.com/assets/9136821/7294007/fbd8044e-e9a9-11e4-80c0-58122b9d1b78.png)
And when I select it:
![screen shot 2015-04-23 at 11 15 16](https://cloud.githubusercontent.com/assets/9136821/7294028/1278fa50-e9aa-11e4-8c00-b8ab0cf2e7b7.png)
Viceversa if I set transparent the background of the image, here the image: 
![screen shot 2015-04-23 at 11 17 09](https://cloud.githubusercontent.com/assets/9136821/7294061/506a762c-e9aa-11e4-9c96-d9c4dbade7ac.png)
![screen shot 2015-04-23 at 11 17 00](https://cloud.githubusercontent.com/assets/9136821/7294064/56ce2680-e9aa-11e4-9d6f-f839b1eba25b.png)

**Comment by Meiguro** [comment]
Thanks for reporting the issue! For whatever reason, `menu_cell_basic_draw` on basalt does not automatically alpha blend. This will eventually make it to CloudPebble when the color support is better.

**Comment by ishepard** [comment]
Ok works like a magic! Thank you!
PS: don't worry, we don't use CloudPebble ;)

**Comment by srabenhorst** [comment]
How do I set the background of an icon?

**Comment by Meiguro** [comment]
Hey @srabenhorst, I responded to your ticket #55, but I'll also answer your question here. With the fix in #55, you would make sure your image only has black and white and no antialiasing.

Without the fix in #55 and just the fix in this ticket, #42, you would set the pixels that are part of the background to be fully transparent (alpha 255), and they would no longer incorrectly highlight. The only issue then is that you'd have to set the icon color to anything other than black or white.

**Comment by fletchto99** [comment]
@meiguro the issue regarding icons appears to be fixed now, both here and in cloud pebble. However, menus still don't appear to support colors in the text portions (title, subtitle...).

Does this ticket also refer to that issue? I'm working on a fix now, however I'm unsure how to handle text colors when the menu item is selected. If the text is black, it should be inverted to appear correctly, like menus currently do. But should this same inversion affect also happen to colors? I would assume not; if the text is red then it should stay red. But what about for darker colors like dark gray for example? Invert it to light gray? (And all other special cases, like dark purple, etc...)

Hopefully i can figure something out for this, then submit a PR.

**Comment by fletchto99** [comment]
@meiguro the issue regarding icons appears to be fixed now, both here and in cloud pebble. However, menus still don't appear to support colors in the text portions (title, subtitle...).

Does this ticket also refer to that issue? I'm working on a fix now, however I'm unsure how to handle text colors when the menu item is selected. If the text is black, it should be inverted to appear correctly, like menus currently do. But should this same inversion affect also happen to colors? I would assume not; if the text is red then it should stay red. But what about for darker colors like dark gray for example? Invert it to light gray? (And all other special cases, like dark purple, etc...)

Hopefully i can figure something out for this, then submit a PR.

**Comment by Meiguro** [comment]
Thanks everyone, open a new issue if there are any other color-lacking areas.
