### ISSUE TITLE
Application crashes after animation on SDK3

### ISSUE THREAD

**Issue by pautomas** [pebble/pebblejs#52]
How to reproduce:

- Clone Pebblejs (tested with cd2a2ddba6a83631b440a7bfdee385c6e0e65e3d)
- Replace app.js with the following code:

```javascript
var UI = require('ui');
var Vector2 = require('vector2');

var wind = new UI.Window();
var rect = new UI.Rect({ size : new Vector2(20,20) });

wind.show();

wind.add(rect);
rect.animate({ position : new Vector2(40,40) });
```

- Build and install the app. I'm using the following command:
 ```pebble build pebble install && build/pebblejs-master.pbw```

- Application will start. Show a rectangle on the top-left corner and run the animation. When the animation finishes the application crashes. 

- No error appears on ```pebble logs```.

Tested with SDK3 dp8 and beta-10 (using a modified version of pebbleJS to make it compatible) on OS X 10.10.2 (14C1514)

**Comment by Meiguro** [comment]
Thanks for reporting the issue, and the minimal example! Previously, pebble.js was freeing the animation itself rather than using animation_destroy.
