### ISSUE TITLE
Not able to set textColor

### ISSUE THREAD

**Issue by idoodler** [pebble/pebblejs#54]
Hi, I am just adapting my WatchApp for the Pebble Time and I noticed that there is no way to set the textColor of a UI.Card. I cant find anything documented.

**Comment by Meiguro** [comment]
Pebble.js is behind in adopting all Pebble SDK capabilities, but I've just added Card titleColor, subtitleColor, and bodyColor in master. Let me know if that suits your needs!

```
// Example
var card = new UI.Card({ title: 'Color!', titleColor: 'red' });
card.show();
```

**Comment by idoodler** [comment]
Awesome thanks!

**Comment by mattmattmatt** [comment]
Thanks, very helpful!
This should be [in the official documentation](https://developer.pebble.com/docs/pebblejs/#card). Now I wonder what else is possible that I just don't know about.
