### ISSUE TITLE
Menu item icon inversion not working anymore

### ISSUE THREAD

**Issue by mactr0n** [pebble/pebblejs#55]
I updated to the latest pebble SDK (Beta10) and also have the latest pebblejs code. Now all item icons are not anymore inverted when selected:
![pebble-screenshot_2015-05-09_12-43-23](https://cloud.githubusercontent.com/assets/4246554/7549996/b3028bd8-f64f-11e4-8934-8ecf4882900f.png)
It should look like this:
![screenshot_main_top](https://cloud.githubusercontent.com/assets/4246554/7549998/d5dc1ef8-f64f-11e4-91ce-118fb45ee0b8.png)

**Comment by Meiguro** [comment]
Thanks for posting! There seems to be an issue with the toolchain causing the inversion in the Basalt Menu Layer not to function, so I implement faux inversion for images with strictly black and white palettes as a work around (see the patch notes for more details).

However, this will only work with images that do not use anti-aliasing. It looks like your power buttons have anti-aliasing, so even the faux inversion won't work for them. You'll want to reduce them to strictly black and white.

If you are willing to develop specifically for Basalt only, completely sidestepping this inversion issue, you would use color and transparency in your icons. Here is an example of how it would look:

![pebble-screenshot_2015-05-11_02-59-20]
(https://cloud.githubusercontent.com/assets/4428900/7562611/9d8efc00-f78a-11e4-84b5-2ed37729d7a3.png) ![pebble-screenshot_2015-05-11_03-13-13](https://cloud.githubusercontent.com/assets/4428900/7562755/ae229030-f78b-11e4-838a-efd805340a37.png)

**Comment by mactr0n** [comment]
Thank you the fix worked perfectly! :+1:
