### ISSUE TITLE
Cannot modify body of UI.Card within click handler

### ISSUE THREAD

**Issue by otbe** [pebble/pebblejs#56]
Hi,

its not possible for me to change the body of a UI.Card element within a click handler or ajax callback. I try something like that:

```
var screen = new UI.Card({
      title: 'Name',
      body: 'Test',
      action: {
        up: 'images/action_icon_plus.png',
        down: 'images/action_icon_minus.png'
      }
    }); 
    
screen.on('click', 'up', function() {
    screen.body('Test2');
});

screen.show();
```

The body changes to 'Test2' but the app crashes with no log output.
Whats wrong with my attempt?

Im using cloudpebble with a Pebble Steel (latest firmware).

**Comment by Meiguro** [comment]
Very sorry about that! I just made a fix. The patch notes explains the issue briefly. I'll close this when it's merged into CloudPebble.

**Comment by otbe** [comment]
Thank you very much. I'll be waiting for the merge :)

**Comment by andreipopovici** [comment]
Hi there,

Strangely, I have a similar issue almost exactly a year later :) Here's the code:

```
var UI = require('ui');
var Voice = require('ui/voice');

var card = new UI.Card({
  title:'Ready',
  body:'Press Select to dictate'
});

card.on('click', function(e) {
    Voice.dictate('start', true, function(e) {
      card.title('');
      card.subtitle('Heard:');
      card.body(e.transcription);
    });
});

card.show();
```

This crashes without log output (doesn't help that CloudPebble returns a 403 for the debug.json from Heroku!).

I'm compiling on Chalk using Pebble.js in CloudPebble, firmware v3.12 on my PTR.

Ninja edit: well ain't that something. I just recompiled and ran the exact same code now, and it doesn't crash anymore. Wonder what changed in the last hour... Huh.

Either way, leaving this here for reference in case it happens to anyone else.

**Comment by Meiguro** [comment]
Ah yes, this is a problem with the voice window not being a normal window. I've created a new ticket for this issue, I'll try to think of something to fix it! https://github.com/pebble/pebblejs/issues/165

I'll post in this ticket too when I fix the issue.

**Comment by Meiguro** [comment]
As for the original issue, the fix is now merged in CloudPebble.

**Comment by andreipopovici** [comment]
Thanks for taking a look! Just to be clear, when you say the fix is merged in CloudPebble, do I get the latest merged version each time I compile? Do I need to change anything else anywhere?
