### ISSUE TITLE
Scrolling Menu item titles

### ISSUE THREAD

**Issue by fletchto99** [pebble/pebblejs#58]
Hey there,

I was wondering if it would be possible to add a sliding/scrolling animation for menu titles whose names are too long. For example my app creates dynamic menu items based off of some Meetup Event names from Meetup.com, however some of these names are too long. Some of them begin with "Pebble smartwatch..." Where the title should be "Pebble Smartwatch Houston Meetup" however the truncated version of the title doesn't really provide much information about the Meetup group. *I could just remove "Pebble Smartwatch" from the title of the group, but the scrolling banner would be more optimal plus this would not work for every menu item, since they don't all begin with that specific string*

Here is what I mean by a scrollable menu title: http://l.wigflip.com/LsSwtWlM/signbot.gif (this kind of concept)

Here is an example of the menu items being truncated: http://i.gyazo.com/b55d0b073a3e8eac9aefd35bc02524bc.png

Thanks in advanced!

**Comment by FabianBeiner** [comment]
:+1:

**Comment by fletchto99** [comment]
Ah shoot I missed that one, thanks @FabianBeiner
