### ISSUE TITLE
Disappearing Menu Items - Scrolling Quickly

### ISSUE THREAD

**Issue by fletchto99** [pebble/pebblejs#59]
When scrolling quickly in a menu, the items sometimes "Dissappear" or don't load. I'm assuming this is the way you manage rendering large dynamic lists, considering the pebble has limited working memory. However this is an issue when scrolling quickly as it can almost seem like the app is lagging or broken. A few of my users have reported it to me but it appears it wasn't on my end. 

Here is a gif of the issue in action: http://i.gyazo.com/a4254d50539cba1643a678035aecf424.gif

Perhaps a work around can be to render x-n and x+n menu items, so when you scroll there's always a buffer of items ahead of you, and then as you scroll down the the upcoming x+n menu item is rendered and ready to go, while the x-n menu item is destroyed?

**Comment by mactr0n** [comment]
My app has the same problem!

**Comment by fletchto99** [comment]
@mactr0n I've created a workaround for this issue by caching and preloading up to 100 menu items at a time. The reason this is a work around and not a fix is because if your menu items have images, loading 100 of them with icons will quickly fill up your Memory during runtime. If your just using simple menus without icons my fix should be fine: https://github.com/fletchto99/Pebble-Meetup/commit/de82c39275bb85a7889aea9aa8333d8ad98f2077

Check out my modifications in that commit to the last two files (menu.js and simply_menu.c)

I'm also working on a way to show "loading" as the title until the menu item is actually loaded from the phone.

**Comment by fletchto99** [comment]
@mactr0n I've created a workaround for this issue by caching and preloading up to 100 menu items at a time. The reason this is a work around and not a fix is because if your menu items have images, loading 100 of them with icons will quickly fill up your Memory during runtime. If your just using simple menus without icons my fix should be fine: https://github.com/fletchto99/Pebble-Meetup/commit/de82c39275bb85a7889aea9aa8333d8ad98f2077

Check out my modifications in that commit to the last two files (menu.js and simply_menu.c)

I'm also working on a way to show "loading" as the title until the menu item is actually loaded from the phone.

**Comment by fletchto99** [comment]
This appears to be fixed now.
