### ISSUE TITLE
Aplite or Basalt

### ISSUE THREAD

**Issue by kropochev** [pebble/pebblejs#64]
How to detect hardware differences in js?
There is a solution similar to this?
```
#ifdef PBL_COLOR
  ...
#else
  ...
#endif
```

**Comment by fletchto99** [comment]
@kropochev PebbleJS is designed to detect the platform running and display the elements based on what's avaliable. However if you wish to display only specific information on a platform then you can use Pebblekit JS directly in your PebbleJS app. Here's a simple example

`var UI = require('ui');

var body;

var basalt = false;

//Determine if getActiveWatchInfo function is defined, if so SDK > 3.0
if(Pebble.getActiveWatchInfo) { //There exists Pebble.getActiveWatchInfo().platform; however it appears to be broken. I'll check into this further
    body = 'PebbleKit JS ready on Basalt!';
    basalt = true;
} else {
    // This is the Aplite platform, getActiveWatchinfo is unavaliable in SDK versions < 3.0
    body = 'PebbleKit JS ready on Aplite!';
}

//A simple card to display the results
new UI.Card({
  title: 'Watch Info',
  subtitle: 'Using Pebble JS',
  body: body
}).show();
`

**Comment by kropochev** [comment]
Thank you very much!
