### ISSUE TITLE
Provide a Pebble.js API for the WakeUp API

### ISSUE THREAD

**Issue by sarfata** [pebble/pebblejs#7]
This new Pebble API is very interesting for pebble.js. We should have an API for it.

**Comment by Meiguro** [comment]
There is now documentation for the implementation!

Here is also a very dry example using all of the available functions:
https://gist.github.com/Meiguro/0deada2525b16ec91e15

There's also `Clock.weekday` for setting recurring alarms. Feel free to reopen or start a new issue if there are any problems.
