### ISSUE TITLE
Image object with colored PNGs

### ISSUE THREAD

**Issue by kinncj** [pebble/pebblejs#73]
Is it possible to check the device type so `Basalt` can display `colored` images instead of `Grayscale` ?
https://github.com/pebble/pebblejs/blob/master/src/js/lib/image.js#L169
https://github.com/pebble/pebblejs/blob/master/src/js/lib/image.js#L13

**Comment by matism** [comment]
Hi there,

you can use different images for aplite and basalt by simply appending ~bw / ~color to your filenames. So if you have one image with the name example you need to create example~bw.png and example~color.png. Within the appinfo.json you only need to add example.png once because the app will automatically use the correct image.

```
      {
        "type": "png",
        "name": "IMAGE_EXAMPLE",
        "file": "images/example.png"
      },
```

Hope that helps,
Mathias

**Comment by Meiguro** [comment]
@matism Thanks for replying! This is a helpful tip I should add to the README.md. @kinncj is referring to colored remote images that are loaded from the internet which I've demoed yesterday at the Toronto meetup but will be pushing up hopefully before the weekend.

**Comment by matism** [comment]
@Meiguro Ah I see, wasn't clear to me so I thought that might help.

**Comment by kinncj** [comment]
@matism, sorry for not being clear.
I figured that local and remote resources can use the same `Image` object, but the `Image::load()` method forces the *Image* to be grayscale.

Thanks.

**Comment by matism** [comment]
@kinncj Now everything is clear to me - thanks for the explanation!

**Comment by Meiguro** [comment]
@kinncj The changes have been pushed! I recommend testing on a real watch. There seems to be a strange app message issue when used in the emulator that I haven't finished investigating, though it eventually still works. If using the emulator, continually press buttons until an image shows up. I plan to add a progress spinner for loading images later, though the progress spinner wouldn't solve the problem with the emulator.

**Comment by kinncj** [comment]
@Meiguro it worked like a charm.
Is cloud pebble using master? I did not have a chance to test on CloudPebble yet, just locally.

**Comment by kinncj** [comment]
@Meiguro I guess we can close this?

**Comment by Meiguro** [comment]
Yes, thanks for the reminder!
