### ISSUE TITLE
[IMPROVEMENT] Ability to display distant image

### ISSUE THREAD

**Issue by WoodySlum** [pebble/pebblejs#8]
Is it possible to display a PNG on a distant server ?

Didin't succeed in doing this, opened a thread  : http://forums.getpebble.com/discussion/17903/pebble-js-display-image-from-distant-server

Tried several ways, without success

**Comment by jgrayillustrate** [comment]
It would be nice, maybe, to be able to use data-url images as well.

**Comment by Meiguro** [comment]
data-url is an interesting idea, I'll keep that in mind.

There was some progress on this ticket with e1ace40bc57e2427475ccd7e2ec5779c726cfdcf. That merge allows images larger than 2K to load. I may improve this to have a progress bar since it's not exactly the best user experience. It's also still lacking an onload callback for knowing when the image is done loading.

Be sure to add the suffix `#width:144` when loading remote images that are not resized for the pebble as noted in the forum post. Using a smaller width is even better. When this ticket is fully implemented I'll be sure to update the documentation on that.

**Comment by WoodySlum** [comment]
Ok I'll do a test to display my home connected camera on my Pebble.
First, I prepared image for Pebble with GD and PHP : 

	if ($this->isPebble) {
		header("Content-type: image/png");
		$size = getimagesizefromstring($img);
		imagefilter($image, IMG_FILTER_GRAYSCALE);
		imagefilter($image, IMG_FILTER_CONTRAST, -255);
		$width = $size[0];
		$height = $size[1];
		$coeff = ((144*100)/$width)/100;
		$newWidth = $width*$coeff;
		$newHeight = $height*$coeff;
		$resizeImage = @imagecreatetruecolor(intval($newWidth), intval($newHeight));
		imagecopyresized($resizeImage, $image, 0, 0, 0, 0, $newWidth, $newHeight, $width, $height);
		ob_start (); 
		 	imagepng ($resizeImage);
			$img = ob_get_contents (); 
		ob_end_clean ();
	}

This will resize picture and transform image to greyscale.
Then I used code you described above : 

	var camUrl = baseUrl + 'method=getCamera&pebble=true#width:144';
	if (camImage != null) {
		cameraContainer.remove(camImage);    
	}

	console.log(camUrl);
	var camImage = new UI.Image({
		position: new Vector2(0, 0),
		size: new Vector2(144, 168),
		image: camUrl
	});

	console.log('Adding image !');
	cameraContainer.add(camImage);
	cameraContainer.show();

And it works great !
Anyway, the watchapp crashes sometimes after displaying image.
Thanks for the work !

**Comment by Meiguro** [comment]
That's great to hear, and you're welcome! It actually has dithering built in too. It's much more impressive with that turned on. Use `#width:144,dither` to both set the width and turn on dithering.

Ah, it must be running out of memory somehow. Thanks for reporting the crash. It already flushes the resource cache when changing windows. Perhaps I should also add reference counting to flush particular images in a long standing window. I'll look into this further.

For anyone else fiddling, it currently only supports PNG's using the wonderful library at https://github.com/devongovett/png.js/. I'll be adding JPEG and GIF support after all the kinks in remote loading are ironed out.

**Comment by WoodySlum** [comment]
I managed the image removal with an event, and the app crash less often.

	cameraContainer.on('hide', function(e) {
		 console.log('Removing camera image');
		camImage.remove();
	});

For me the issue can be closed. Thank you it works like a charm.
